In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [9]:
vector = np.array([30,29,35,37,39,40,38])
print(len(vector))

7


In [10]:
matrix = np.array([[1,2,3],[3,4,5],[6,7,7]])
print(matrix)
print(len(matrix))

[[1 2 3]
 [3 4 5]
 [6 7 7]]
3


In [11]:
tensor = np.array([
    [
        [11,12],[13,14],[15,16],[17,18]
    ],
    [
        [21,22],[23,24],[25,26],[27,28]
    ]
])
print(tensor)

[[[11 12]
  [13 14]
  [15 16]
  [17 18]]

 [[21 22]
  [23 24]
  [25 26]
  [27 28]]]


## Metodos de numpy

In [13]:
array_range = np.arange(1,11)
print(array_range)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# Matriz indentidad
matriz_identidad = np.eye(5)
print(matriz_identidad)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# Matriz diagonal
matriz_diag = np.diag([1,2,3,4])
print(matriz_diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [17]:
# Uso de random
random_numpy = np.random.random((3,5))
print(random_numpy)

[[0.46765976 0.35932293 0.9371061  0.08366691 0.82201554]
 [0.98775826 0.23159401 0.13190632 0.28638349 0.11929011]
 [0.44382062 0.54855005 0.04652756 0.88748771 0.82076197]]
