# Operaciones principales en Algebra lineal
## Suma

In [14]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A, B)

Suma = A + B
print(Suma)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


La multiplicación de matrices combina filas de una matriz con columnas de otra. Por ejemplo, si tenemos las mismas matrices A y B seria la fila por la columna
La multiplicación se puede realizar usando la función dot o @
A @ B
np.dot(A, B)

In [15]:
producto = A @ B
producto_doc = np.dot(A, B)
print(producto)
print(producto_doc)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Transpuesta
La transpuesta de una matríz intercambia sus filas y columnas puedo realizar la transpuesta directamente con python utilizando T
Con numpy utilizo np.transpose(matriz)

In [16]:
A_tranpouse = A.T
print(A_tranpouse)
print("---"*10)
E = [[1,2,3],
     [4,5,6],
     [7,8,9]
    ]
#e_trans = E.T
numpy_trans = np.transpose(E)
print(numpy_trans)

[[1 3]
 [2 4]]
------------------------------
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Determinante
El determinante es un valor único --  se calcula utilizando np.linalg.det(A)

In [17]:
determinante = np.linalg.det(A)
print(determinante)

-2.0000000000000004


#Inversa de una matriz

In [18]:
inversa = np.linalg.inv(A)
print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]
