# Operaciones principales en Algebra lineal
## Suma

In [4]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A, B)

Suma = A + B
print(Suma)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


La multiplicación de matrices combina filas de una matriz con columnas de otra. Por ejemplo, si tenemos las mismas matrices A y B seria la fila por la columna
La multiplicación se puede realizar usando la función dot o @
A @ B
np.dot(A, B)

In [7]:
producto = A @ B
producto_doc = np.dot(A, B)
print(producto)
print(producto_doc)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Transpuesta
La transpuesta de una matríz intercambia sus filas y columnas