# Broadcasting


In [1]:
import numpy as np

In [4]:
prices = np.array([100,200,300,400,500])
discount = np.array([0.9])
prices_with_discount = prices * discount
print(prices_with_discount)

[ 90. 180. 270. 360. 450.]


In [10]:
prices2 = np.random.randint(100,500, size=(3,3))
plus = np.array([10,20,30])
prices_with_plus = prices2 + plus
print(prices2)
print(prices_with_plus)

[[210 484 481]
 [205 234 491]
 [212 342 494]]
[[220 504 511]
 [215 254 521]
 [222 362 524]]


## Some arrays methods using Numpy
[Documentación métodos de arrays con Numpy](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-methods)

[Doc. para manipular arrays](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

In [17]:
Matrix = np.arange(2, 6)
# Buscar si todos son mayores un número - Devuelve un boleano
print(np.all(Matrix > 1))
# Si existe alguno any
print(np.any(Matrix == 15))

True
False


In [35]:
Matrix = np.arange(1, 10).reshape(3, 3)
array_a = Matrix[0:1,:].flatten()
array_b = Matrix[1:2,:].flatten()
array_c = np.array([7,8,9])
print(array_c)
concatenated_a = np.concatenate((array_a, array_b))
concatenated_b = np.concatenate((array_a, array_a))
print(concatenated_a, concatenated_b, sep="\n=================\n")

[7 8 9]
[1 2 3 4 5 6]
[1 2 3 1 2 3]
