# Indexación y Slicing

In [ ]:
import numpy as np

arreglo = np.array([i for i in range(10, 110, 10)])
print(arreglo, f"Tamaño arreglo: {len(arreglo)}" , arreglo[-2], sep=" -- ")
print(" ---  " * 20)
print("Última posición: {}, Penúltima:{}, Del primero al tercero {}".format(arreglo[-1], arreglo[-2], arreglo[0:3]))

In [34]:
# Indexación Booleana
arreglo2 = np.array([x for x in range(0, 22, 2)])
print(arreglo2)
bool_index = arreglo2 > 10
print(bool_index,end="\n ------------------------------ \n")

index_del_arreglo = [2,4,10,1]
print(arreglo2[index_del_arreglo])


[ 0  2  4  6  8 10 12 14 16 18 20]
[False False False False False False  True  True  True  True  True]
 ------------------------------ 
[ 4  8 20  2]


In [45]:
array3 = np.random.randint(1,20, size=(3,3))
print(array3)
print(array3[0,2], end="\n ============= \n")
print(array3[:2,:2]) # Array con las dos primeras filas y 2 columnas
print(array3[:3,:2]) # Array con las dos primeras filas y 2 columnas

[[17 18 15]
 [ 8 16  1]
 [ 9  1  2]]
15
[[17 18]
 [ 8 16]]
[[17 18]
 [ 8 16]
 [ 9  1]]


In [ ]:
""" Ejercicio 1: Acceder a elementos específicos:
    Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.
"""
example = [i for i in range(1,11)]
print(f"Acceder al cuarto: {example[3]}, --- penúltimo elemento: {example[-2]} = {example[(len(example) - 2)]}" )

Acceder al cuarto: 4, --- penúltimo elemento: 9 = 9


In [58]:
""" Ejercicio 2: Slicing de arreglos:
    Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos 
    de las últimas 5 posiciones.
"""
array_num = [x for x in range(1,21)]
print(array_num)
print(array_num[3:8])
print(array_num[-1:-4:-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[4, 5, 6, 7, 8]
[20, 19, 18]


In [ ]:
""" Ejercicio 3: Indexing con booleanos:
Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.

Ejercicio 4: Indexación con múltiples índices:
Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.

Ejercicio 5: Matrices bidimensionales:
Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.
"""