# Indexación y Slicing

In [2]:
import numpy as np

#arreglo = np.array([i for i in range(10, 110, 10)]) esta es la forma clásica de realizarlo con python.
arreglo = np.arange(10,110, 10)
print(arreglo, f"Tamaño arreglo: {len(arreglo)}" , arreglo[-2], sep=" -- ")
print(" ---  " * 20)
print("Última posición: {}, Penúltima:{}, Del primero al tercero {}".format(arreglo[-1], arreglo[-2], arreglo[0:3]))

[ 10  20  30  40  50  60  70  80  90 100] -- Tamaño arreglo: 10 -- 90
 ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---   ---  
Última posición: 100, Penúltima:90, Del primero al tercero [10 20 30]


In [ ]:
# Indexación Booleana
arreglo2 = np.array([x for x in range(0, 22, 2)])
print(arreglo2)
bool_index = arreglo2 > 10
print(bool_index,end="\n ------------------------------ \n")

index_del_arreglo = [2,4,10,1]
print(arreglo2[index_del_arreglo])


In [ ]:
array3 = np.random.randint(1,20, size=(3,3))
print(array3)
print(array3[0,2], end="\n ============= \n")
print(array3[:2,:2]) # Array con las dos primeras filas y 2 columnas
print(array3[:3,:2]) # Array con las dos primeras filas y 2 columnas

In [ ]:
""" Ejercicio 1: Acceder a elementos específicos:
    Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.
"""
example = [i for i in range(1,11)]
print(f"Acceder al cuarto: {example[3]}, --- penúltimo elemento: {example[-2]} = {example[(len(example) - 2)]}" )

In [ ]:
""" Ejercicio 2: Slicing de arreglos:
    Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos 
    de las últimas 5 posiciones.
"""
array_num = [x for x in range(1,21)]
print(array_num)
print(array_num[3:8])
print(array_num[-1:-4:-1])

In [19]:
""" Ejercicio 3: Indexing con booleanos:
Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.
"""
a = np.random.randint(0, 100, size=100)
mayores = a > 50
#print(mayores)
print(a[mayores], len(a[mayores]))

[54 83 72 73 88 84 81 63 95 96 92 92 90 53 63 86 64 64 51 80 74 89 63 82
 87 89 84 53 80 59 51 78 65 62 65 78 58 93 98 77 82 68 62 99 76 79 97 72
 55 56 66 72 61 57 90 66 83] 57


In [20]:
"""
Ejercicio 4: Indexación con múltiples índices:
Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.
"""
b = np.random.randint(5,30, size=8)
print(b)
positions = [0,3,5]
print(b[positions])

[17 24 13 13  7 22 28 14]
[17 13 22]


In [24]:
"""
Ejercicio 5: Matrices bidimensionales:
Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.
"""
matriz_bidimensional = np.random.randint(10,50, size=(4,4))
print(matriz_bidimensional)
slicing_inferior_derecho = matriz_bidimensional[2:,2:]
print(slicing_inferior_derecho)



[[39 42 44 48]
 [49 36 19 41]
 [28 19 23 10]
 [28 44 21 26]]
[[23 10]
 [21 26]]


In [ ]:
""" 
Ejercicio 6: Matrices bidimensionales:
De la siguiente matriz 7x7
[
    [11, 12, 13, 14, 15, 16, 17],
    [21, 22, 23, 24, 25, 26, 27],
    [31, 32, 33, 34, 35, 36, 37],
    [41, 42, 43, 44, 45, 46, 47],
    [51, 52, 53, 54, 55, 56, 57],
    [61, 62, 63, 64, 65, 66, 67],
    [71, 72, 73, 74, 75, 76, 77],
]

a - Accede a la submatriz de 4x4 ubicada en la esquina superior derecha.
b - Accede a la submatriz de 3x2 ubicada en la esquina superior izquierda.
c - Accede a la submatriz de 3x2 ubicada en la esquina inferior derecha.
d - Accede a la submatriz de 2x3 ubicada en la esquina inferior izquierda.
e - Accede a la submatriz de 4x3 ubicada desde la fila 3 y la columna 4.
f - Accede a la submatriz de 3x3 de tal modo que quede centrada.
g - Accede a la submatriz de 3x2 ubicada desde la fila 4 y la columna 3.
h - Accede a la submatriz de 2x3 ubicada desde la fila 2 y la columna 5.
i - Accede a la submatriz de 5x5 de tal modo que quede centrada.
J - Accede a la submatriz de 6x6 2x3 ubicada desde la fila 2 y la columna 2.
"""
matriz_base = np.array([
    [11, 12, 13, 14, 15, 16, 17],
    [21, 22, 23, 24, 25, 26, 27],
    [31, 32, 33, 34, 35, 36, 37],
    [41, 42, 43, 44, 45, 46, 47],
    [51, 52, 53, 54, 55, 56, 57],
    [61, 62, 63, 64, 65, 66, 67],
    [71, 72, 73, 74, 75, 76, 77],
    ]
)
#print(matriz_base, end="\n\n")
#a - Accede a la submatriz de 4x4 ubicada en la esquina superior derecha.
a = matriz_base[:4,3:]
print(a)

[[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]
 [51 52 53 54 55 56 57]
 [61 62 63 64 65 66 67]
 [71 72 73 74 75 76 77]]

[[14 15 16 17]
 [24 25 26 27]
 [34 35 36 37]
 [44 45 46 47]]


In [8]:
# b - Accede a la submatriz de 3x2 ubicada en la esquina superior izquierda.
b = matriz_base[:3,:2]
print(b)

[[11 12]
 [21 22]
 [31 32]]


In [9]:
#c - Accede a la submatriz de 3x2 ubicada en la esquina inferior derecha.
c = matriz_base[4:,5:]
print(c)

[[56 57]
 [66 67]
 [76 77]]
