In [1]:
import numpy as np

In [ ]:
# Matriz transpuesta
matriz_base_1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
transpuesta = matriz_base_1.T
print(transpuesta)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
matriz_base_2 = np.arange(1,13)
print(matriz_base_2)
reshape_array = matriz_base_2.reshape(3,4)
reshape_array_6x2 = matriz_base_2.reshape(6,2)
reshape_array_4x3 = matriz_base_2.reshape(4,3)
print("Reshape 3x4: \n",reshape_array)
print("Reshape 6x2: \n",reshape_array_6x2)
print("Reshape 4x3: \n",reshape_array_4x3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape 3x4: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape 6x2: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Reshape 4x3: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# Invertir arrays
array_base = np.arange(1,13)
inverso = array_base[::-1]
print(inverso)

[12 11 10  9  8  7  6  5  4  3  2  1]


In [19]:
matriz_base_3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
flattened = matriz_base_3.flatten()
print(flattened)

[1 2 3 4 5 6 7 8 9]
