# Métodos


In [3]:
import numpy as np

In [6]:

survey_response = np.array([
    "bueno", "excelente", "bueno", "malo",
    "excelente", "bueno" , "bueno", "malo",
    "bueno", "excelente","excelente", "bueno", "malo"
])

print(np.unique(survey_response))

unique_elements, counts = np.unique(survey_response, return_counts=True)
print(unique_elements, counts)

['bueno' 'excelente' 'malo']
['bueno' 'excelente' 'malo'] [6 4 3]


## Vistas o Copias

In [11]:
# Si se hace de estar forma se pasa por referencia y el cambio de una altera la otra
array_x = np.arange(10)
view_y = array_x[1:3]
print(array_x, view_y)
array_x[1:3] = [10, 11]
print(array_x, view_y)
view_y[1] = 15
print(array_x, view_y)

# Para evitar el paso por referencia utilizo COPY
copy_x = array_x[[1,2]]
print(array_x, view_y, copy_x)
array_x[1:3] = [12,13]
print(array_x, view_y, copy_x)



[0 1 2 3 4 5 6 7 8 9] [1 2]
[ 0 10 11  3  4  5  6  7  8  9] [10 11]
[ 0 10 15  3  4  5  6  7  8  9] [10 15]
[ 0 10 15  3  4  5  6  7  8  9] [10 15] [10 15]
[ 0 12 13  3  4  5  6  7  8  9] [12 13] [10 15]
